
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181  
    networks:
      - clickhouse-kafka_clickhouse_network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - clickhouse-kafka_clickhouse_network

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - clickhouse-kafka_clickhouse_network

  producer:
    build:
      context: ./producer
    depends_on:
      - kafka
    networks:
      - clickhouse-kafka_clickhouse_network
    command: ["/bin/sh"]
    tty: true
    stdin_open: true

  consumer1:
    build:
      context: ./consumer1
    depends_on:
      - kafka
      - clickhouse
    networks:
      - clickhouse-kafka_clickhouse_network
    command: ["/bin/sh"]
    tty: true
    stdin_open: true

  consumer2:
    build:
      context: ./consumer2
    depends_on:
      - kafka
      - clickhouse
    networks:
      - clickhouse-kafka_clickhouse_network
    command: ["/bin/sh"]
    tty: true
    stdin_open: true    

networks:
  clickhouse-kafka_clickhouse_network:
    external: true

volumes:
  clickhouse_data:
